### ISSUE TITLE
9_multinomial_regression_1.pdf

### ISSUE THREAD

**Issue by victoriaquance** [sjbonner/stat_9055_readings#1]
not 100% confidence changing these myself :) 

line 156, "show" how? 

line 160, "coefficient" typo 

line 177, "invertebrates" typo

also should be R^J -> R^{J-1}, as you mentioned in class

**Comment by sjbonner** [comment]
Resolved by #[d54c82e](https://github.com/sjbonner/stat_9055_readings/commit/d54c82e4b720ab0ff968115175bd8eb3eeec1707). Thanks @victoriaquance .
